/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/addresses/{address_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Address
         * @description Everything filed at one address, with each offer's evidence and freshness.
         */
        get: operations["address_addresses__address_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/addresses/{address_id}/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Address Options
         * @description What can be bought here, best first, from what is already known.
         *
         *     Nothing is asked of an operator on this path. A page that waits eight seconds for three
         *     checkers is a page nobody sees the end of, so the stored answer is served at once and
         *     `known` says, per operator, whether asking would add anything.
         */
        get: operations["address_options_addresses__address_id__options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/addresses/{address_id}/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Address Probe
         * @description Ask the operators that are due, and keep what they say.
         *
         *     One operator at a time is the caller's choice, and the reason it exists: a checker takes
         *     between two and eight seconds, and three of them behind one request means the reader
         *     waits for the slowest before learning anything. Asked separately, each lands when it
         *     lands.
         *
         *     The one path here that leaves the building. It is slow by nature, it is a write, and it
         *     is rate limited at the proxy for the same reasons the report endpoint is.
         */
        post: operations["address_probe_addresses__address_id__probe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Whether the database answers, and whether it has been built.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/adapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Adapter Health
         * @description How each operator's checker is faring, derived from what happened when it was asked.
         *
         *     Not stored anywhere: a status field is one more thing that can be stale while the thing
         *     it describes has moved on.
         */
        get: operations["adapter_health_health_adapters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/municipalities.geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Regions
         * @description Every municipality, with how much of it fibre reaches.
         *
         *     The zooms where the country fits on the screen are the zooms where a street is a
         *     fraction of a pixel, and this map has no basemap under it. Without these the first thing
         *     anyone sees is a black rectangle. All 333 go at once because 333 is small, and they are
         *     simplified to a tolerance a country-wide view cannot tell from the truth.
         */
        get: operations["regions_municipalities_geojson_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report
         * @description Record that something here looks wrong.
         *
         *     The only write in the API. Rate limiting belongs at the reverse proxy rather than in
         *     process, where it would be per worker and reset on deploy.
         */
        post: operations["report_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Addresses and streets, in Greek or Greeklish, folded the way the index was built.
         */
        get: operations["search_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streets.geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Streets In
         * @description The streets in a viewport, in the shape the tiles use.
         *
         *     The map is meant to be served from a PMTiles archive, which is one file a web server can
         *     range-request and is what should be in front of real traffic. This is the same data by
         *     the other road: it needs no build step, so the renderer can be worked on and checked
         *     against a live database before any tiles are cut, and it is the fallback where an
         *     archive has not been copied across yet.
         *
         *     Both paths carry the fields the tile schema names, because a renderer that works against
         *     one and not the other is worth nothing.
         */
        get: operations["streets_in_streets_geojson_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streets/{street_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Street
         * @description A street where no address is filed: coverage comes from the cabinets it crosses.
         */
        get: operations["street_streets__street_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/streets/{street_id}/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask For
         * @description Make the address at this number, so it can be probed and kept like any other.
         *
         *     The register knows the street and not the number, which is the common case rather than
         *     the odd one: it files nothing at all on some streets and the Cosmote scrape walked away
         *     from others after five empty numbers in a row. Refusing the reader their own front door
         *     because nobody filed it is the wrong answer when we hold the street it is on.
         *
         *     A write, and the second one in this API, so it is rate limited at the proxy alongside
         *     the report and the probe. It is idempotent: the same number on the same street is the
         *     same address however many times it is asked for.
         */
        post: operations["ask_for_streets__street_id__addresses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddressDetail */
        AddressDetail: {
            /**
             * Connected
             * @description null when not filed, not false
             */
            connected: boolean | null;
            /** Id */
            id: number;
            /** Lat */
            lat: number;
            /** Locality */
            locality: string | null;
            /** Lon */
            lon: number;
            /** Municipality */
            municipality: string | null;
            /** Offers */
            offers: components["schemas"]["Offer"][];
            /** Postcode */
            postcode: string | null;
            /** Premises */
            premises: number | null;
            /** Street */
            street: string;
            /** Street No */
            street_no: string | null;
            /** Vhcn */
            vhcn: boolean | null;
        };
        /** Asking */
        Asking: {
            /**
             * Street No
             * @description as the reader typed it
             */
            street_no: string;
        };
        /** Buyable */
        Buyable: {
            /**
             * Basis
             * @description quoted, measured, filed or advertised
             */
            basis: string;
            /**
             * Confidence
             * @description evidence from tests alone; a quote has none
             */
            confidence: number;
            /** @description null when a part of it was never published */
            cost: components["schemas"]["Cost"] | null;
            /**
             * Data Cap Gb
             * @description null is unlimited, not unknown
             */
            data_cap_gb: number | null;
            /**
             * Enough
             * @description covers an ordinary household, on speed and allowance
             */
            enough: boolean;
            /**
             * Expected Mbps
             * @description null when nothing here can say
             */
            expected_mbps: string | null;
            /** Family */
            family: string;
            /** Plan */
            plan: string;
            /**
             * Provider
             * @description the code every join uses
             */
            provider: string;
            /**
             * Provider Name
             * @description what the reader is shown
             */
            provider_name: string;
            /** Technology */
            technology: string;
            /**
             * Tests
             * @description measurements behind it, zero when it rests on none
             */
            tests: number;
            /** Why */
            why: string;
        };
        /**
         * Cost
         * @description A monthly cost in its parts, so a card can say why a cheap headline is not cheap.
         */
        Cost: {
            /** Recurring */
            recurring: string;
            /** Total */
            total: string;
            /**
             * Upfront
             * @description setup and equipment, spread over the window
             */
            upfront: string;
        };
        /** Drawn */
        Drawn: {
            /** Features */
            features: {
                [key: string]: unknown;
            }[];
            /**
             * Truncated
             * @description more streets are in view than were sent; the reader should zoom in
             */
            truncated: boolean;
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Addresses
             * @description rows in the address index
             */
            addresses: number;
            /**
             * Offers
             * @description rows in address_coverage
             */
            offers: number;
            /** Ok */
            ok: boolean;
        };
        /** Offer */
        Offer: {
            /** Available From */
            available_from: string | null;
            /** Family */
            family: string;
            /**
             * Infra Provider
             * @description who built it, when not the seller
             */
            infra_provider: string | null;
            /**
             * Matched By
             * @description point for a filing here, area for a cabinet
             */
            matched_by: string;
            /** Provider */
            provider: string;
            /** Provider Name */
            provider_name: string;
            /** @description null when the operator filed no speed */
            speed: components["schemas"]["Speed"] | null;
            /** Technology */
            technology: string;
        };
        /** Operator */
        Operator: {
            /**
             * Known
             * @description how this operator's answer was arrived at
             */
            known: string;
            /** Provider */
            provider: string;
            /** Provider Name */
            provider_name: string;
            /**
             * Says
             * @description what to tell the reader when it is not answering
             */
            says: string;
            /**
             * State
             * @description healthy, degraded, broken or untried
             */
            state: string;
        };
        /** Options */
        Options: {
            /** Address Id */
            address_id: number;
            /**
             * Known
             * @description per operator: how the answer was arrived at
             */
            known: {
                [key: string]: string;
            };
            /**
             * Need Mbps
             * @description the bar used, which the caller may move
             */
            need_mbps: string;
            /**
             * Operators
             * @description an operator missing from a comparison is a worse lie than a visible gap
             */
            operators: components["schemas"]["Operator"][];
            /** Options */
            options: components["schemas"]["Buyable"][];
        };
        /** Probed */
        Probed: {
            /**
             * Asked
             * @description false when the operator was inside its backoff
             */
            asked: boolean;
            /** Detail */
            detail: string | null;
            /** Provider */
            provider: string;
            /**
             * Reached
             * @description false when the checker could not be reached at all
             */
            reached: boolean;
            /**
             * Serviceable
             * @description null when nothing conclusive came back
             */
            serviceable: boolean | null;
        };
        /** Report */
        Report: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
        };
        /** ReportIn */
        ReportIn: {
            /**
             * Address Id
             * @description the address it is about
             */
            address_id?: number | null;
            /**
             * Contact
             * @description optional, to reply
             */
            contact?: string | null;
            /**
             * Detail
             * @description what looks wrong
             */
            detail: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "availability" | "price" | "address" | "other";
            /** Plan Id */
            plan_id?: number | null;
            /** Provider Id */
            provider_id?: number | null;
        };
        /** Result */
        Result: {
            /**
             * Best Mbps
             * @description the fastest known to reach here; null is not filed, not zero
             */
            best_mbps: string | null;
            /** Id */
            id: number;
            /**
             * Kind
             * @description address, street, or proposed
             */
            kind: string;
            /**
             * Locality
             * @description as the register filed it
             */
            locality: string | null;
            /**
             * Match
             * @description prefix, word, fuzzy or asked
             */
            match: string;
            /** Municipality */
            municipality: string | null;
            /** Name */
            name: string;
            /** Postcode */
            postcode: string | null;
            /**
             * Premises
             * @description dwellings passed, null when not filed
             */
            premises: number | null;
            /**
             * Street Id
             * @description for a proposed address, the street to ask for it on
             */
            street_id?: number | null;
            /** Street No */
            street_no: string | null;
        };
        /** Speed */
        Speed: {
            /** Band */
            band: number;
            /** Label */
            label: string;
            /**
             * Max Mbps
             * @description null on the open-ended top band
             */
            max_mbps: number | null;
            /**
             * Min Mbps
             * @description null on the open-ended bottom band
             */
            min_mbps: number | null;
        };
        /** StreetDetail */
        StreetDetail: {
            /**
             * Bbox
             * @description west, south, east, north — a street has no point, only an extent
             */
            bbox: [
                number,
                number,
                number,
                number
            ];
            /** Highway */
            highway: string;
            /** Id */
            id: number;
            /** Municipality */
            municipality: string | null;
            /** Name */
            name: string;
            /** Offers */
            offers: components["schemas"]["Offer"][];
            /**
             * Ways
             * @description OSM ways merged into this street
             */
            ways: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    address_addresses__address_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    address_options_addresses__address_id__options_get: {
        parameters: {
            query?: {
                need_mbps?: number | string;
            };
            header?: never;
            path: {
                address_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Options"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    address_probe_addresses__address_id__probe_post: {
        parameters: {
            query?: {
                /** @description ask only these; omit to ask every operator that is due */
                provider?: string[] | null;
            };
            header?: never;
            path: {
                address_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Probed"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    adapter_health_health_adapters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operator"][];
                };
            };
        };
    };
    regions_municipalities_geojson_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Drawn"];
                };
            };
        };
    };
    report_reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_search_get: {
        parameters: {
            query: {
                /** @description street, optionally with a town */
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    streets_in_streets_geojson_get: {
        parameters: {
            query: {
                west: number;
                south: number;
                east: number;
                north: number;
                zoom: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Drawn"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    street_streets__street_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                street_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreetDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_for_streets__street_id__addresses_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                street_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Asking"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
